routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\ProductosController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/administrador',  [UserController::class, 'index'], function () {
    return view('administrador');
})->middleware(['auth', 'verified'])->name('administrador');


Route::get('/user', function () {
    return view('user');
})->middleware(['auth', 'verified'])->name('user');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('productos', ProductosController::class);
});

Route::post('/register', [UserController::class, 'processRegistration'])->name('register');

Route::get('/mi-nueva-ruta', function () {
    return 'Hola, esta es mi nueva ruta!';
});

Route::get('register', [RegisteredUserController::class, 'create'])
->name('register');

Route::post('register', [RegisteredUserController::class, 'store']);

Route::post('/emails', [EmailController::class, 'store'])->name('emails.store');

//nuevas

Route::get('/promociones', function () {
    return view('promociones');
});

Route::get('/compras', function () {
    return view('compras');
});

Route::get('/proveedores', function () {
    return view('proveedores');
});
Route::get('/mapas', function () {
    return view('mapas');
});

Route::resource('clientes', ClientesController::class);




require __DIR__.'/auth.php';

app/Models/Productos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Productos extends Model
{
    use HasFactory;
    protected $table = 'Productos';
    protected $fillable = [
        'Nombre', 'Precio', 'Descripcion', 'Estado', 'imagen', 'min', 'max', 'stock'
        ];

}

app/Http/Controllers/ProductosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Productos;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class ProductosController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $productos = Productos::latest()->paginate(5);

        return view('productos.index', compact('productos'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('productos.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'Nombre' => 'required',
            'Precio' => 'required',
            'Descripcion' => 'required',
            'Estado' => 'required',
            'imagen' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'min' => 'required',
            'max' => 'required',
            'stock' => 'required',
        ]);

        $imagenNombre = time().'.'.$request->imagen->extension();
        $request->imagen->move(public_path('imagenes'), $imagenNombre);

        Productos::create([
            'Nombre' => $request->Nombre,
            'Precio' => $request->Precio,
            'Descripcion' => $request->Descripcion,
            'Estado' => $request->Estado,
            'imagen' => $imagenNombre,
            'min' => $request->min,
            'max' => $request->max,
            'stock' => $request->stock,
        ]);

        return redirect()->route('productos.index')
            ->with('success', 'Producto creado exitosamente.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Productos $producto): View
    {
        return view('productos.show', compact('producto'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Productos $producto): View
    {
        return view('productos.edit', compact('producto'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Productos $producto): RedirectResponse
    {
        $request->validate([
            'Nombre' => 'required',
            'Precio' => 'required',
            'Descripcion' => 'required',
            'Estado' => 'required',
            'imagen' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',

        ]);

        if ($request->hasFile('imagen')) {
            $imagenNombre = time().'.'.$request->imagen->extension();
            $request->imagen->move(public_path('imagenes'), $imagenNombre);
            $producto->imagen = $imagenNombre;
        }

        $producto->Nombre = $request->Nombre;
        $producto->Precio = $request->Precio;
        $producto->Descripcion = $request->Descripcion;
        $producto->Estado = $request->Estado;
        $producto->save();

        return redirect()->route('productos.index')
            ->with('success', 'Producto actualizado exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Productos $producto): RedirectResponse
    {
        $producto->delete();

        return redirect()->route('productos.index')
            ->with('success', 'Producto eliminado exitosamente.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/productos/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Crear nuevo producto:') }}
            <a class="btn btn-success" href="{{ route('productos.index') }}">Atras</a>
        </h2>
    </x-slot>
    <div class="container text-white">

@if ($errors->any())
    <div class="alert alert-danger">
    <strong>¡Ups!</strong> Hubo algunos problemas con tus datos.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('productos.store') }}" method="POST" enctype="multipart/form-data">
    @csrf

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                <input type="text" name="Nombre" class="form-control bg-secondary">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Precio:</strong>
                <input type="number" name="Precio" class="form-control bg-secondary">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Descripción:</strong>
                <input type="text" name="Descripcion" class="form-control bg-secondary">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Estado:</strong>
                <input type="number" name="Estado" class="form-control bg-secondary">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Imagen:</strong>
                <input type="file" name="imagen" class="form-control-file bg-secondary">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Min:</strong>
                <input type="number" name="min" class="form-control bg-secondary">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Max:</strong>
                <input type="number" name="max" class="form-control bg-secondary">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Stock:</strong>
                <input type="number" name="stock" class="form-control bg-secondary">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Registrar</button>
        </div>
    </div>

</form>
</div>

</x-app-layout>

resources/views/productos/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Editar porducto:') }}
            <a class="btn btn-success" href="{{ route('productos.index') }}">Atras</a>
        </h2>
    </x-slot>
    <div class="container">
<br>
<div class="row text-white">


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>¡Ups!</strong> Hubo algunos problemas con tus datos.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('productos.update', $producto->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nombre:</strong>
                    <input type="text" name="Nombre" value="{{ $producto->Nombre }}" class="form-control" placeholder="Nombre">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Precio:</strong>
                    <input type="text" name="Precio" value="{{ $producto->Precio }}" class="form-control" placeholder="Precio">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Descripción:</strong>
                    <input type="text" name="Descripcion" value="{{ $producto->Descripcion }}" class="form-control" placeholder="Descripcion">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Estado:</strong>
                    <select name="Estado" class="form-control">
                        <option value="1" {{ $producto->Estado == 1 ? 'selected' : '' }}>Activo</option>
                        <option value="0" {{ $producto->Estado == 0 ? 'selected' : '' }}>Inactivo</option>
                    </select>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Imagen:</strong>
                    <input type="file" name="imagen" class="form-control-file">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
        </div>

    </form>

</div>

</x-app-layout>

resources/views/productos/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Lista de Productos:') }}
            <a class="btn btn-success" href="{{ route('productos.create') }}">Crear nuevo producto</a>

        </h2>
    </x-slot>

    <div class="container">


        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif

        <br>

        <table class="table bg-black text-white">
            <tr>
                <th>No</th>
                <th>Nombre</th>
                <th>Foto</th>
                <th width="280px">Acción</th>
            </tr>
            @foreach ($productos as $producto)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $producto->Nombre }}</td>
                <td>
                        @if ($producto->imagen)
                            <img src="{{ asset('imagenes/' . $producto->imagen) }}" alt="Imagen del producto" width="50">
                        @else
                            Sin imagen
                        @endif
                    </td>
                <td>
                    <form action="{{ route('productos.destroy', $producto->id) }}" method="POST">

                        <a class="btn btn-info" href="{{ route('productos.show', $producto->id) }}">Mostrar</a>

                        <a class="btn btn-primary" href="{{ route('productos.edit', $producto->id) }}">Editar</a>

                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </table>

        {!! $productos->links() !!}

</div>
</x-app-layout>

resources/views/productos/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 10 CRUD Application - ItSolutionStuff.com</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
    @yield('content')
</div>

</body>
</html>

resources/views/productos/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Ver detalles del productos:') }}
            <a class="btn btn-success" href="{{ route('productos.index') }}">Atras</a>

        </h2>
    </x-slot>

    <div class="container text-white text-center justify-content-center align-items-center">
        <br><br>
        <div class="row">
            <div class="col-6">
                <img class="img-fluid" src="{{ asset('imagenes/' . $producto->imagen) }}" alt="ynv">
            </div>
            <div class="col-6 text-white bg success">
                <ul class="list-group">
                    <li class="list-group-item text-white bg-success">
                        <strong>Nombre:</strong>
                        {{ $producto->Nombre }}
                    </li>
                    <li class="list-group-item text-white bg-success">
                        <strong>Precio:</strong>
                        {{ $producto->Precio }}
                    </li>
                    <li class="list-group-item text-white bg-success">
                        <strong>Descripción:</strong>
                        {{ $producto->Descripcion }}
                    </li>
                    <li class="list-group-item text-white bg-success">
                        <strong>Estado:</strong>
                        {{ $producto->Estado }}
                    </li>
                    <li class="list-group-item text-white bg-success">
                        <strong>Stock Mínimo:</strong>
                        {{ $producto->min }}
                    </li>
                    <li class="list-group-item text-white bg-success">
                        <strong>Stock Máximo:</strong>
                        {{ $producto->max }}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</x-app-layout>